### ISSUE TITLE
Insulator Health Classification NN Inference Performance Benchmark

### ISSUE THREAD

**Issue by stephenwang5** [kite-capstone/meishur-mission#1]
Given an ONNX model, which of the 3 available `onnxruntime` execution providers gives us the best performance?

Let's compare the **inference speed** and **memory usage** for running a given ONNX model (the YOLOv8 model we found on Roboflow converted to OPset 16) on

1. TensorrtExecutionProvider
2. CPUExecutionProvider
3. CUDAExecutionProvider

I suggest using a sequence of ~1000 images as input. Could be broken into batches of 32, 16, 1, or other sizes. A bar graph comparing the metrics and the batch sizes would be perfect.

**Comment by niobiumneo** [comment]
Was set to cudaexceution provider for reliability and faster processing
